#!/bin/bash
usage="Usage:  $0 [xml] [name] [output path] [primitive directory]
        xml               path to xml file
        name              (default: 'machine') used to create output directory
        output path       directory to store generated files
        primitive source  (default: ./PRIMITIVES) directory containing gsl files

Use an xml file to    1) generate yaml file for machine and 
                      2) generate isonomic permutations(cli,gui,iot,etc...)

Generated files are stored in created directory structure.
For example:
    ./codegen.sh ~/foo.xml machine_foo ~/machine_foo
produces the output:
                      ~/machine_foo/
                      ~/machine_foo/machine.yaml
                      ~/machine_foo/generated/<files>
"
# show usage if run without arguments
: ${1?"$usage"}
#if run without second argument use 'machine'
#as default
machine_xml=$1
name=${2:-machine}
machine_path=${3:-./machine}
primitive_source=${4:-./PRIMITIVES}

while getopts ':hs:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    esac
done
shift $((OPTIND - 1))


gsl -a -script:machine_yaml.gsl $machine_xml $name $machine_path
# create a title using the input xml file and the
# latest git commit of the project where the file resides
title="$(basename $machine_xml)"@"$(cd $machine_path && git rev-parse HEAD)"
# machine_path trailing slash is important!
gsl -title:$title -a -script:permutate.gsl $machine_xml $machine_path/generated/ $primitive_source 
# check generated yaml
#python3 check_yaml.py $machine_path/$name.yaml
dot $machine_path/generated/permutations.dot -Grankdir=LR -Tsvg -o $machine_path/generated/permutations.svg

echo "### $title

![partial map][rel-map-svg]

[rel-map-svg]: permutations.svg?sanitize=true

Generated permutations and partial map

This file generated by [codegen](https://github.com/galencm/ma)

[Mozilla Public License, v. 2.0](http://mozilla.org/MPL/2.0/)" > $machine_path/generated/README.md
